// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLnh1KGM0yRE9mUXP9vzNmDWowA3jYBg',
    appId: '1:165163098882:web:4e7c3ce9d65ff98c9d981b',
    messagingSenderId: '165163098882',
    projectId: 'smarn-fet',
    authDomain: 'smarn-fet.firebaseapp.com',
    storageBucket: 'smarn-fet.appspot.com',
    measurementId: 'G-NGFP0YVZCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzZj5CRk029u7fBhF1pcF7ytGJlxmDhw',
    appId: '1:165163098882:android:273b81d58556812a9d981b',
    messagingSenderId: '165163098882',
    projectId: 'smarn-fet',
    storageBucket: 'smarn-fet.appspot.com',
  );
}